.TH "C:/Users/diogo/Desktop/trabalhoLP2_18855_Fase3-master/trabalhoLP2_18855_Fase3-master/DGS2/Dados Directory Reference" 3 "Fri Jun 26 2020" "Dados" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/diogo/Desktop/trabalhoLP2_18855_Fase3-master/trabalhoLP2_18855_Fase3-master/DGS2/Dados Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCasosDL\&.cs\fP"
.br
.ti -1c
.RI "file \fBRecuperadosDL\&.cs\fP"
.br
.in -1c
