.TH "C:/Users/diogo/Desktop/trabalhoLP2_18855_Fase3-master/trabalhoLP2_18855_Fase3-master/DGS2/Dados/CasosDL.cs" 3 "Fri Jun 26 2020" "Dados" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/diogo/Desktop/trabalhoLP2_18855_Fase3-master/trabalhoLP2_18855_Fase3-master/DGS2/Dados/CasosDL.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDados\&.CasosDL\fP"
.br
.RI "Classe CasosDL\&.Trabalha com os dados da classe Caso "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDados\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Dados from the source code\&.
