.TH "Dados" 3 "Fri Jun 26 2020" "Dados" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dados
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCasosDL\fP"
.br
.RI "Classe CasosDL\&.Trabalha com os dados da classe Caso "
.ti -1c
.RI "class \fBRecuperadosDL\fP"
.br
.RI "Classe RecuperadosDL\&.Trabalha com os dados da classe Recuperado\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Dados from the source code\&.
