.TH "Regras" 3 "Fri Jun 26 2020" "Regras" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Regras
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBValidar\fP"
.br
.RI "Classe \fBValidar\fP\&. Aplica regras de acordo com os dados recebidos da biblioteca Dados e Classes\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regras from the source code\&.
