.TH "Regras.Validar" 3 "Fri Jun 26 2020" "Regras" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Regras.Validar \- Classe \fBValidar\fP\&. Aplica regras de acordo com os dados recebidos da biblioteca Dados e Classes\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBInsertNewCase\fP (Caso c, int perfil)"
.br
.RI "Insere um novo caso\&. "
.ti -1c
.RI "static bool \fBInsertNewRecover\fP (Recuperados x, int perfil)"
.br
.RI "Insere um novo recuperado\&. "
.in -1c
.SH "Detailed Description"
.PP 
Classe \fBValidar\fP\&. Aplica regras de acordo com os dados recebidos da biblioteca Dados e Classes\&. 


.SH "Member Function Documentation"
.PP 
.SS "static bool Regras\&.Validar\&.InsertNewCase (Caso c, int perfil)\fC [static]\fP"

.PP
Insere um novo caso\&. 
.PP
\fBParameters\fP
.RS 4
\fIc\fP 
.br
\fIperfil\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.SS "static bool Regras\&.Validar\&.InsertNewRecover (Recuperados x, int perfil)\fC [static]\fP"

.PP
Insere um novo recuperado\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP 
.br
\fIperfil\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Regras from the source code\&.
