.TH "C:/Users/diogo/Desktop/trabalhoLP2_18855_Fase3-master/trabalhoLP2_18855_Fase3-master/DGS2/Regras/Validar.cs" 3 "Fri Jun 26 2020" "Regras" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/diogo/Desktop/trabalhoLP2_18855_Fase3-master/trabalhoLP2_18855_Fase3-master/DGS2/Regras/Validar.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRegras\&.Validar\fP"
.br
.RI "Classe \fBValidar\fP\&. Aplica regras de acordo com os dados recebidos da biblioteca Dados e Classes\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBRegras\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Regras from the source code\&.
