.TH "C:/Users/diogo/Desktop/trabalhoLP2_18855_Fase3-master/trabalhoLP2_18855_Fase3-master/DGS2/DgsValidacoes Directory Reference" 3 "Fri Jun 26 2020" "BusinessObject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/diogo/Desktop/trabalhoLP2_18855_Fase3-master/trabalhoLP2_18855_Fase3-master/DGS2/DgsValidacoes Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCaso\&.cs\fP"
.br
.ti -1c
.RI "file \fBObito\&.cs\fP"
.br
.ti -1c
.RI "file \fBPessoa\&.cs\fP"
.br
.ti -1c
.RI "file \fBRecuperado\&.cs\fP"
.br
.in -1c
