.TH "C:/Users/diogo/Desktop/trabalhoLP2_18855_Fase3-master/trabalhoLP2_18855_Fase3-master/DGS2/DgsValidacoes/Caso.cs" 3 "Fri Jun 26 2020" "BusinessObject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/diogo/Desktop/trabalhoLP2_18855_Fase3-master/trabalhoLP2_18855_Fase3-master/DGS2/DgsValidacoes/Caso.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBClasses\&.Caso\fP"
.br
.RI "Classe caso\&.Define um caso "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBClasses\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BusinessObject from the source code\&.
