.TH "Classes.Obitos" 3 "Fri Jun 26 2020" "BusinessObject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Classes.Obitos \- Classe Obitos\&.Define um obito  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBClasses\&.Pessoa\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBCausas\fP { \fBCausas\&.Covid\fP, \fBCausas\&.Gripe\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBObitos\fP ()"
.br
.ti -1c
.RI "\fBObitos\fP (string nNome, string rRegiao, int iIdade, string gGenero, \fBCausas\fP cCausa)"
.br
.RI "Construtor com dados do exterior "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBCausas\fP \fBCausa\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Classe Obitos\&.Define um obito 


.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBClasses\&.Obitos\&.Causas\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICovid \fP\fP
.TP
\fB\fIGripe \fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Classes\&.Obitos\&.Obitos ()"

.SS "Classes\&.Obitos\&.Obitos (string nNome, string rRegiao, int iIdade, string gGenero, \fBCausas\fP cCausa)"

.PP
Construtor com dados do exterior 
.PP
\fBParameters\fP
.RS 4
\fIrRegiao\fP 
.br
\fIiIdade\fP 
.br
\fIgGenero\fP 
.br
\fIcMorte\fP 
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "\fBCausas\fP Classes\&.Obitos\&.Causa\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for BusinessObject from the source code\&.
