.TH "Classes.Pessoa" 3 "Fri Jun 26 2020" "BusinessObject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Classes.Pessoa \- Classe Pessoa\&.Define uma pessoa\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBClasses\&.Caso\fP, \fBClasses\&.Obitos\fP, and \fBClasses\&.Recuperados\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPessoa\fP ()"
.br
.ti -1c
.RI "\fBPessoa\fP (string nNome, string rRegiao, int iIdade, string gGenero)"
.br
.RI "Construtor com dados do exterior "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "string \fBregiao\fP"
.br
.ti -1c
.RI "int \fBidades\fP"
.br
.ti -1c
.RI "string \fBgenero\fP"
.br
.ti -1c
.RI "string \fBnome\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBNome\fP\fC [get, set]\fP"
.br
.RI "Manipula atributo 'nome' "
.ti -1c
.RI "string \fBRegiao\fP\fC [get, set]\fP"
.br
.RI "Manipula atributo 'regiao' int regiao; "
.ti -1c
.RI "int \fBIdades\fP\fC [get, set]\fP"
.br
.RI "Manipula atributo 'idade' int idades; "
.ti -1c
.RI "string \fBGenero\fP\fC [get, set]\fP"
.br
.RI "Manipula atributo 'genero' int genero; "
.in -1c
.SH "Detailed Description"
.PP 
Classe Pessoa\&.Define uma pessoa\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Classes\&.Pessoa\&.Pessoa ()"

.SS "Classes\&.Pessoa\&.Pessoa (string nNome, string rRegiao, int iIdade, string gGenero)"

.PP
Construtor com dados do exterior 
.PP
\fBParameters\fP
.RS 4
\fIrRegiao\fP 
.br
\fIiIdade\fP 
.br
\fIgGenero\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "string Classes\&.Pessoa\&.genero\fC [protected]\fP"

.SS "int Classes\&.Pessoa\&.idades\fC [protected]\fP"

.SS "string Classes\&.Pessoa\&.nome\fC [protected]\fP"

.SS "string Classes\&.Pessoa\&.regiao\fC [protected]\fP"

.SH "Property Documentation"
.PP 
.SS "string Classes\&.Pessoa\&.Genero\fC [get]\fP, \fC [set]\fP"

.PP
Manipula atributo 'genero' int genero; 
.SS "int Classes\&.Pessoa\&.Idades\fC [get]\fP, \fC [set]\fP"

.PP
Manipula atributo 'idade' int idades; 
.SS "string Classes\&.Pessoa\&.Nome\fC [get]\fP, \fC [set]\fP"

.PP
Manipula atributo 'nome' 
.SS "string Classes\&.Pessoa\&.Regiao\fC [get]\fP, \fC [set]\fP"

.PP
Manipula atributo 'regiao' int regiao; 

.SH "Author"
.PP 
Generated automatically by Doxygen for BusinessObject from the source code\&.
