.TH "Classes" 3 "Fri Jun 26 2020" "BusinessObject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Classes
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCaso\fP"
.br
.RI "Classe caso\&.Define um caso "
.ti -1c
.RI "class \fBObitos\fP"
.br
.RI "Classe Obitos\&.Define um obito "
.ti -1c
.RI "class \fBPessoa\fP"
.br
.RI "Classe Pessoa\&.Define uma pessoa\&. "
.ti -1c
.RI "class \fBRecuperados\fP"
.br
.RI "Classe Recuperados\&.Define um recuperado "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BusinessObject from the source code\&.
