.TH "Classes.Caso" 3 "Fri Jun 26 2020" "BusinessObject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Classes.Caso \- Classe caso\&.Define um caso  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBClasses\&.Pessoa\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCaso\fP ()"
.br
.ti -1c
.RI "\fBCaso\fP (string nNome, string rRegiao, int iIdade, string gGenero, string dDoenteRisco)"
.br
.RI "Construtor com dados do exterior "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "string \fBdoenteRisco\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBDDoenteRisco\fP\fC [get, set]\fP"
.br
.RI "Manipula atributo doenteRisco "
.in -1c
.SH "Detailed Description"
.PP 
Classe caso\&.Define um caso 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Classes\&.Caso\&.Caso ()"

.SS "Classes\&.Caso\&.Caso (string nNome, string rRegiao, int iIdade, string gGenero, string dDoenteRisco)"

.PP
Construtor com dados do exterior 
.PP
\fBParameters\fP
.RS 4
\fIrRegiao\fP 
.br
\fIiIdade\fP 
.br
\fIgGenero\fP 
.br
\fIdDoenteRisco\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "string Classes\&.Caso\&.doenteRisco\fC [protected]\fP"

.SH "Property Documentation"
.PP 
.SS "string Classes\&.Caso\&.DDoenteRisco\fC [get]\fP, \fC [set]\fP"

.PP
Manipula atributo doenteRisco 

.SH "Author"
.PP 
Generated automatically by Doxygen for BusinessObject from the source code\&.
