.TH "Classes" 3 "Fri Jun 26 2020" "DGS2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Classes \- Mainspace do programa\&. Neste espaço, a classe principal(Program), é que irá chamar e executar todos os métodos\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProgram\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Mainspace do programa\&. Neste espaço, a classe principal(Program), é que irá chamar e executar todos os métodos\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for DGS2 from the source code\&.
