.TH "C:/Users/diogo/Desktop/trabalhoLP2_18855_Fase3-master/trabalhoLP2_18855_Fase3-master/Dgs/Program.cs" 3 "Fri Jun 26 2020" "DGS2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/diogo/Desktop/trabalhoLP2_18855_Fase3-master/trabalhoLP2_18855_Fase3-master/Dgs/Program.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBClasses\&.Program\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBClasses\fP"
.br
.RI "Mainspace do programa\&. Neste espaço, a classe principal(Program), é que irá chamar e executar todos os métodos\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DGS2 from the source code\&.
